artifact_uri: ./../mlflow/0/ef09a68d79c34ec7a55f18b974d9a315/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: ef09a68d79c34ec7a55f18b974d9a315
run_uuid: ef09a68d79c34ec7a55f18b974d9a315
source_name: ''
source_type: 4
source_version: ''
start_time: 1595593548680
status: 1
tags: []
user_id: unknown
