artifact_uri: ./../mlflow/0/39c23d5fc4ef454b94e1c30730b2d2bf/artifacts
end_time: null
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
name: ''
run_id: 39c23d5fc4ef454b94e1c30730b2d2bf
run_uuid: 39c23d5fc4ef454b94e1c30730b2d2bf
source_name: ''
source_type: 4
source_version: ''
start_time: 1595593570362
status: 1
tags: []
user_id: unknown
